stages:
  - test_optimized

variables:
  CACHE_ROOT: "../.cache"
  BAZEL_CACHE: "$CACHE_ROOT/bazel"
  BAZELISK_CACHE: "$CACHE_ROOT/bazelisk"

cache: &x86_64_cache
  key: x86_64
  paths:
    - "$bazel-user_root"
  policy: pull-push

x86_64-tests:
  stage: test_optimized
  script:
    - XDG_CACHE_HOME="$BAZELISK_CACHE" ./bazelisk-linux-amd64 --output_user_root="$BAZEL_CACHE" test -c opt //...
    - XDG_CACHE_HOME="$BAZELISK_CACHE" ./bazelisk-linux-amd64 --output_user_root="$BAZEL_CACHE" test -c dbg //third_party/gtest:gtest_test
  cache:
    <<: *x86_64_cache
