stages:
  - force_cache_hydration
  - test_optimized

variables:
  LOCAL_CACHE_ROOT: ".cache"
  LOCAL_BAZEL_CACHE: "$LOCAL_CACHE_ROOT/bazel"
  LOCAL_BAZELISK_CACHE: "$LOCAL_CACHE_ROOT/bazelisk"

x86_64-optimized-tests:
  stage: test_optimized
  cache:
    key: x86_64_cache
    paths:
      - "$LOCAL_BAZEL_CACHE"
      - "$LOCAL_BAZELISK_CACHE"
  before_script:
    - mkdir -p "$LOCAL_CACHE_ROOT"
    - touch "$LOCAL_CACHE_ROOT/DO_NOT_BUILD_HERE"
  script:
    - find "$LOCAL_CACHE_ROOT" -type f
    - XDG_CACHE_HOME="$LOCAL_BAZELISK_CACHE" ./bazelisk-linux-amd64 --output_user_root="$LOCAL_BAZEL_CACHE" test -c opt //...
