default:
  image:
    name: gcr.io/bazel-public/bazel:5.3.2
    entrypoint: [""]

variables:
  LOCAL_CACHE_ROOT: ".cache"
  BAZEL_CACHE_LOCATION: "/home/ubuntu/.cache"

.cache_setup:
  before_script:
    - rm -rf "$BAZEL_CACHE_LOCATION"
    - mv "$LOCAL_CACHE_ROOT" "$BAZEL_CACHE_LOCATION"
  after_script:
    - rm -rf "$LOCAL_CACHE_ROOT"
    - mv "$BAZEL_CACHE_LOCATION" "$LOCAL_CACHE_ROOT"

stages:
  - test

x86_64-optimized-tests:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
  cache:
    key: optimized_bin_cache
    paths:
      - "$LOCAL_CACHE_ROOT"
  before_script:
    - !reference [.cache_setup, before_script]
  after_script:
    - !reference [.cache_setup, after_script]
  script:
    - bazel --output_base=$BAZEL_CACHE_LOCATION test -c opt //buffer/... //io/...
  artifacts:
    name: "test_logs"
    paths:
      - "**/test.log"
    expire_in: 1 week
