default:
  image:
    name: gcr.io/bazel-public/bazel:5.3.2
    entrypoint: [""]

variables:
  LOCAL_CACHE_ROOT: ".cache"
  LOCAL_BAZEL_CACHE: "$LOCAL_CACHE_ROOT/bazel"

.cache_setup:
  before_script:
    - mkdir -p "$LOCAL_CACHE_ROOT" "$LOCAL_BAZEL_CACHE"
    - touch "$LOCAL_CACHE_ROOT/DO_NOT_BUILD_HERE"
    - touch "$LOCAL_CACHE_ROOT/BUILD.bazel"
    - touch "$LOCAL_BAZEL_CACHE/DO_NOT_BUILD_HERE"

stages:
  - test

x86_64-optimized-tests:
  stage: test
  cache:
    key: optimized_bin_cache
    paths:
      - "$LOCAL_BAZEL_CACHE"
  before_script:
    - !reference [.cache_setup, before_script]
  script:
    - bazel test --disk_cache=$LOCAL_BAZEL_CACHE -c opt -- //... -//$LOCAL_CACHE_ROOT/...
