stages:
  - test

variables:
  bazel-user-root: .cache/bazel

cache: &x86_64_cache
  key: x86_64
  paths:
    - "$bazel-user_root"
  policy: pull-push

debug-test-job:
  stage: test
  script:
    - ./bazelisk-linux-amd64 --output_user_root="$bazel-user-root" test -c dbg //gtest:gtest_test
  cache:
    <<: *x86_64_cache
    policy: pull

optimized-test-job:
  stage: test
  script:
    - ./bazelisk-linux-amd64 --output_user_root="$bazel-user-root" test -c opt //gtest:gtest_test
  cache:
    <<: *x86_64_cache
