stages:
  - test

variables:
  BAZEL_USER_ROOT: "../.cache/bazel"

cache: &x86_64_cache
  key: x86_64
  paths:
    - "$bazel-user_root"
  policy: pull-push

x86_64-tests:
  stage: test
  script:
    - ./bazelisk-linux-amd64 --output_user_root="$BAZEL_USER_ROOT" test -c opt //...
    - ./bazelisk-linux-amd64 --output_user_root="$BAZEL_USER_ROOT" test -c dbg //third_party/gtest:gtest_test
  cache:
    <<: *x86_64_cache
