#!/bin/sh
set -e

if [ "$1" = "remove" ]
then
    if [ -x "`which systemctl 2>/dev/null`" ]
    then
	for service in "tvsc-virtual-tower" "tvsc-datetime" "tvsc-echo" "tvsc-hello"
	do
	    systemctl stop "${service}"
	    systemctl disable "${service}"
	done
	/sbin/iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 50050
	/sbin/iptables-save -f /etc/iptables/rules.v4
	/sbin/ip6tables-save -f /etc/iptables/rules.v6
    fi
fi
