cc_library(
    name = "store_api",
    hdrs = [
        "store.h",
        "array_store.h",
        "store_string.h",
    ],
    deps = [
        "//iterator",
    ],
)

cc_library(
    name = "buffer",
    hdrs = [
        "blocking_data_sink.h",
        "buffer.h",
        "ring_buffer.h",
    ],
    deps = [
        ":store_api",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "buffer_test",
    srcs = ["buffer_test.cc"],
    deps = [
        ":buffer",
        "//third_party/glog",
        "//third_party/gtest",
    ],
)

cc_test(
    name = "ring_buffer_test",
    srcs = ["ring_buffer_test.cc"],
    deps = [
        ":buffer",
        "//third_party/glog",
        "//third_party/gtest",
    ],
)

cc_test(
    name = "array_store_test",
    srcs = ["array_store_test.cc"],
    deps = [
        ":store_api",
        "//third_party/gtest",
        "//third_party/glog",
    ],
)
